### ISSUE TITLE
Static vs Dynamic

### ISSUE THREAD

**Issue by ClaudeTheCazur** [corpulentgowk/BadMonTing#1]
Have we decided yet? This appears to subscribe to static, which is okay if that's what we all agree on. If not, then we should change the framework, because it will be very difficult and messy to do so later on.

**Comment by corpulentgowk** [comment]
The pages are supposed to be static for the prototype. The website doesn't
need to be complete. It's just supposed to demonstrate 3 representative
tasks. The website is fine as is. The tasks are: visit a candidate profile
page. Compare candidates, change the candidate comparisons. We can also add
a view issues task but it's not important.

Thanks
Steven Layne

On Friday, February 26, 2016, ClaudeTheCazur <notifications@github.com>
wrote:

> Have we decided yet? This appears to subscribe to static, which is okay if
> that's what we all agree on. If not, then we should change the framework,
> because it will be very difficult and messy to do so later on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/corpulentgowk/BadMonTing/issues/1>.
>


-- 
Steven O'Brian Layne
Northwestern University 2017
McCormick School of Engineering and Applied Science
Computer Science
